from uuid import UUID

from source2doc.formatter.mdx import blocks as mdx_blocks
from source2doc.models import docs as doc_models
from source2doc.storage import PostgresStorage

from app.errors import ResourceNotFoundError
from app.routes.docs.dto import (
    BundleInfo,
    PageInfo,
    PageVersionDetailResponse,
    PageVersionListItem,
    RepositoryInfoShort,
)


async def list_bundles(storage: PostgresStorage, limit: int, offset: int) -> list[BundleInfo]:
    bundles_data = await storage.list_bundles(limit=limit, offset=offset)
    result = []
    for bundle in bundles_data:
        repository = None
        if bundle.get("repository"):
            repo_data = bundle["repository"]
            repository = RepositoryInfoShort(
                name=repo_data["name"],
                source_type=repo_data["source_type"],
                git_url=repo_data.get("git_url"),
                git_branch=repo_data.get("git_branch"),
                commit_sha=repo_data.get("commit_sha"),
            )

        total_pages = bundle["pages_count"]
        failed_pages = bundle.get("failed_pages_count", 0) or 0
        result.append(
            BundleInfo(
                id=bundle["id"],
                generation_id=bundle["generation_id"],
                name=bundle.get("name"),
                project_name=bundle.get("project_name"),
                description=bundle.get("description"),
                repo_id=bundle.get("repo_id"),
                created_at=bundle["created_at"],
                updated_at=bundle["updated_at"],
                metadata=bundle.get("metadata", {}),
                pages_count=total_pages,
                failed_pages_count=failed_pages,
                successful_pages_count=max(total_pages - failed_pages, 0),
                repository=repository,
            )
        )

    return result


async def get_bundle_index(storage: PostgresStorage, generation_id: UUID) -> dict:
    index = await storage.get_index(generation_id)
    if not index:
        raise ResourceNotFoundError(resource_type="bundle", resource_id=str(generation_id))
    return index.model_dump()


async def list_bundle_pages(storage: PostgresStorage, generation_id: UUID) -> list[PageInfo]:
    pages_data = await storage.get_bundle_pages(generation_id)
    return [PageInfo(**page) for page in pages_data]


def _render_page_markdown(page: doc_models.DocPage) -> str:
    """Render a stored ``DocPage`` to GitHub-flavored Markdown.

    Pages are persisted as a list of typed blocks (see migration 01) — the
    raw author-supplied Markdown is *not* kept after the writer agent runs,
    so for B6.4 ("Download Markdown" — closes ТЗ ДОК-10) we re-render the
    same blocks the wiki viewer renders, reusing the bundler's GFM
    formatter helpers so the on-disk MkDocs/Nextra/GFM bundle and the
    single-page download stay byte-identical.
    """
    lines: list[str] = [f"# {page.title}", ""]
    if page.summary:
        lines.append(page.summary)
        lines.append("")

    for block in page.blocks:
        lines.extend(mdx_blocks.format_block(block))
        lines.append("")

    if page.related:
        lines.append("## Related Pages")
        lines.append("")
        for related_id in page.related:
            lines.append(f"- [{related_id}](./{related_id}.md)")
        lines.append("")

    return "\n".join(lines)


async def get_page(storage: PostgresStorage, generation_id: UUID, page_id: str) -> dict:
    page = await storage.get_page(generation_id, page_id)
    if not page:
        raise ResourceNotFoundError(resource_type="page", resource_id=page_id)

    payload = page.model_dump()

    # B6.5 — attach the full repository row (incl. ``commit_sha``) so the UI
    # can build "View source" deep-links. ``get_page_repository`` returns
    # ``None`` for local-path bundles; in that case we omit the key entirely
    # (the UI hides the "View source" affordance).
    if hasattr(storage, "get_page_repository"):
        repository = await storage.get_page_repository(generation_id)
        if repository is not None:
            payload["repository"] = RepositoryInfoShort(
                name=repository["name"],
                source_type=repository["source_type"],
                git_url=repository.get("git_url"),
                git_branch=repository.get("git_branch"),
                commit_sha=repository.get("commit_sha"),
            ).model_dump()

    # B6.3 / ТЗ ДОК-09 — attach the dominant LLM model so the wiki badge
    # can show "Generated by claude-opus-4-7" without a second round-trip.
    # ``generated_at`` was already populated on metadata by the storage
    # layer (it lives on the row's ``updated_at``).
    metadata = payload.setdefault("metadata", {})
    metadata["llm_model"] = await storage.get_dominant_model(generation_id)

    # B6.4 / ТЗ ДОК-10 — render the page back to GFM Markdown so the UI
    # can offer a "Download Markdown" button without a second request.
    # The raw markdown isn't persisted (only typed blocks are), so we
    # re-render here using the same formatter the bundler uses for GFM
    # exports — keeping the two paths byte-identical.
    payload["body_markdown"] = _render_page_markdown(page)

    return payload


async def list_page_versions(
    storage: PostgresStorage,
    generation_id: UUID,
    page_id: str,
) -> list[PageVersionListItem]:
    """B11.2 — return the version history for ``page_id``, newest first.

    The ``generation_id`` URL segment scopes the request to a bundle but
    isn't used as a filter (history is per-page across all bundles); we
    still surface 404 when the bundle doesn't recognise the page so the
    UI gets a clear failure mode for stale URLs. The list returned is
    ordered newest-first to match what ``storage.list_page_versions``
    produces — the dropdown re-uses that order without re-sorting.
    """
    page = await storage.get_page(generation_id, page_id)
    if not page:
        raise ResourceNotFoundError(resource_type="page", resource_id=page_id)

    rows = await storage.list_page_versions(page_id)
    return [
        PageVersionListItem(
            generation_id=str(row.generation_id),
            commit_sha=row.commit_sha,
            short_sha=row.commit_sha[:7] if row.commit_sha else None,
            created_at=row.created_at,
        )
        for row in rows
    ]


async def get_page_version(
    storage: PostgresStorage,
    generation_id: UUID,
    page_id: str,
    version_generation_id: UUID,
) -> PageVersionDetailResponse:
    """B11.2 — return a single historical snapshot.

    ``generation_id`` is the bundle the wiki is currently rendering; it
    is *not* required to equal ``version_generation_id`` (the whole
    point is to read across generations). It's only used to scope the
    page existence check, so a request for a page that never lived in
    this bundle returns 404 instead of leaking unrelated history.
    """
    page = await storage.get_page(generation_id, page_id)
    if not page:
        raise ResourceNotFoundError(resource_type="page", resource_id=page_id)

    version = await storage.get_page_version(page_id, version_generation_id)
    if not version:
        raise ResourceNotFoundError(
            resource_type="page_version",
            resource_id=f"{page_id}@{version_generation_id}",
        )

    body = version.body or {}
    metadata = version.metadata or {}
    # Title / summary aren't separate columns on ``page_versions`` — they
    # round-tripped through ``body``. Older snapshots written before this
    # contract may not have them; fall back to the latest row's values
    # (best-effort, the UI tolerates either).
    title = body.get("title") or metadata.get("title") or page.title
    summary = body.get("summary") or page.summary

    return PageVersionDetailResponse(
        page_id=version.page_id,
        generation_id=str(version.generation_id),
        commit_sha=version.commit_sha,
        created_at=version.created_at,
        title=title,
        summary=summary,
        metadata=metadata,
        blocks=body.get("blocks", []) or [],
        related=body.get("related", []) or [],
        body_markdown=version.body_markdown,
    )


async def list_page_symbols(
    storage: PostgresStorage,
    generation_id: UUID,
) -> list[dict]:
    """B6.2 — return the cross-page symbol map for a generation.

    The wiki UI uses this to linkify `Class`/`function()` references across
    pages without requiring the writer agent to emit explicit cross-links.
    """
    rows = await storage.list_page_symbols(generation_id)
    return [
        {"symbol": row["symbol"], "page_id": row["page_id"], "kind": row["kind"]} for row in rows
    ]


async def get_page_graph(
    storage: PostgresStorage,
    generation_id: UUID,
) -> dict:
    """B13.2 — return ``{nodes, edges}`` for the wiki link graph.

    Nodes are derived from ``documentation_pages`` (so isolated pages
    still appear in the graph; the UI can render them as orphans).
    Edges come straight from ``page_links`` for the generation.
    """
    pages = await storage.get_bundle_pages(generation_id)
    edges = await storage.list_page_links(generation_id)

    nodes = [{"id": page["page_id"], "title": page.get("title")} for page in pages]
    edge_dicts = [
        {
            "from": edge.from_page_id,
            "to": edge.to_page_id,
            "kind": edge.kind,
            "weight": edge.weight,
        }
        for edge in edges
    ]
    return {"nodes": nodes, "edges": edge_dicts}


async def list_inbound_links(
    storage: PostgresStorage,
    generation_id: UUID,
    page_id: str,
) -> list[dict]:
    """B13.2 — return the "Referenced by …" list for ``page_id``.

    Joins each inbound edge with its source page's title (if known) so
    the UI can render the link label without a second round-trip. Pages
    that no longer exist in ``documentation_pages`` (e.g. a re-run that
    pruned the source page but left stale edges) keep their raw page_id
    as the title fallback.
    """
    edges = await storage.list_inbound_links(generation_id, page_id)
    if not edges:
        return []

    pages = await storage.get_bundle_pages(generation_id)
    titles = {page["page_id"]: page.get("title") for page in pages}

    return [
        {
            "from_page_id": edge.from_page_id,
            "title": titles.get(edge.from_page_id),
            "kind": edge.kind,
            "weight": edge.weight,
        }
        for edge in edges
    ]
