#!/usr/bin/env bash
# Generates a fresh `.env` with a random Fernet encryption key + bcrypt admin
# password hash. Idempotent — refuses to overwrite an existing `.env`.
#
# Usage:  ./bootstrap.sh
#
# After running, start the stack with:
#   docker compose --profile app up -d --build

set -euo pipefail

cd "$(dirname "$0")"

if [ -f .env ]; then
    echo ".env already exists — refusing to overwrite. Delete it first if you want a fresh bootstrap." >&2
    exit 1
fi

gen_password() {
    # head closes early -> tr gets SIGPIPE; we accept that explicitly so
    # `set -o pipefail` doesn't kill the bootstrap.
    LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom 2>/dev/null | head -c 16 || true
}
ADMIN_PASSWORD="${ADMIN_PASSWORD:-$(gen_password)}"

echo "Generating encryption key..."
ENCRYPTION_KEY=$(./generate-encryption-key.sh)

echo "Hashing admin password..."
ADMIN_PASSWORD_HASH=$(./generate-admin-password.sh "$ADMIN_PASSWORD")

# Docker Compose interpolates `$` in env_file values. bcrypt hashes are full
# of literal `$` (`$2b$12$...`) which compose would otherwise expand against
# empty shell vars and silently corrupt. Double them so compose round-trips
# the hash to the container env unchanged.
ADMIN_PASSWORD_HASH_ESCAPED=${ADMIN_PASSWORD_HASH//\$/\$\$}

cat > .env <<EOF
# Generated by ./bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Re-run by deleting this file and running ./bootstrap.sh again.

# Fernet key. Used by gateway + workers to encrypt/decrypt per-task LLM configs
# in Redis and admin presets in Postgres. MUST match across all services.
ENCRYPTION_KEY=$ENCRYPTION_KEY

# bcrypt hash of the admin password (literal \$ doubled because Docker Compose
# interpolates env_file values). Plaintext was printed once on bootstrap.
ADMIN_PASSWORD_HASH=$ADMIN_PASSWORD_HASH_ESCAPED

# PostgreSQL password — shared by the postgres container, gateway, and workers.
POSTGRES_PASSWORD=docgen_password
EOF

cat <<EOF

============================================================
.env generated.

Admin login:
  username: admin
  password: $ADMIN_PASSWORD

SAVE THIS PASSWORD NOW — it is not stored anywhere else.

Next step:
  docker compose --profile app up -d --build

Then open http://localhost/ and log in at /admin/login.
============================================================
EOF
