import os
from pathlib import Path

from pydantic import BaseModel, Field, field_validator

from source2doc.config import (
    LLMConfig,
    LogfireConfig,
    PostgresConfig,
    QdrantConfig,
    RedisConfig,
    S3Config,
)
from source2doc.loader import load_yaml_config


# Per-mode default liveness ports. Workers run in separate containers so the
# ports never collide in production; the offsets just keep local-dev sane when
# someone runs multiple modes side by side.
DEFAULT_HEALTH_PORTS: dict[str, int] = {
    "docgen": 8100,
    "repos": 8101,
    "bundler": 8102,
    "codetour": 8103,
    "prdoc": 8104,
}


class ModelPricing(BaseModel):
    """Per-model price in USD per 1M tokens (prompt / completion).

    The two-rate split mirrors how OpenAI / Anthropic publish their
    pricing tables. Both fields are required so we don't accidentally
    record a half-priced cost when only one rate is configured.
    """

    prompt_per_1m: float = Field(
        ge=0.0,
        description="USD per 1,000,000 prompt (input) tokens.",
    )
    completion_per_1m: float = Field(
        ge=0.0,
        description="USD per 1,000,000 completion (output) tokens.",
    )


# Default pricing as of 2025-Q4 (USD per 1M tokens, public list prices).
# Numbers are best-effort defaults — operators can override the whole map
# via worker `config.yaml`. Missing models => cost_usd is recorded as null
# rather than crashing the handler.
DEFAULT_MODEL_PRICING: dict[str, ModelPricing] = {
    "gpt-4o": ModelPricing(prompt_per_1m=2.50, completion_per_1m=10.00),
    "gpt-4o-mini": ModelPricing(prompt_per_1m=0.15, completion_per_1m=0.60),
    "claude-opus-4-7": ModelPricing(prompt_per_1m=15.00, completion_per_1m=75.00),
    "claude-sonnet-4-6": ModelPricing(prompt_per_1m=3.00, completion_per_1m=15.00),
    "claude-haiku-4-5": ModelPricing(prompt_per_1m=1.00, completion_per_1m=5.00),
}


class BundlerConfig(BaseModel):
    """Bundler worker tunables."""

    toc_max_depth: int = Field(
        default=2,
        ge=0,
        le=6,
        description=(
            "Maximum heading depth included in the autogenerated full Table of "
            "Contents (toc.json / _toc.md).  ``0`` disables ToC generation."
        ),
    )


class GatewayWorkerConfig(BaseModel):
    worker_id: str = Field(
        default_factory=lambda: os.environ.get("WORKER_ID", "worker-1"),
        description="Worker ID",
    )
    redis: RedisConfig = Field(default_factory=RedisConfig)
    postgres: PostgresConfig = Field(default_factory=PostgresConfig)
    s3: S3Config = Field(default_factory=S3Config)
    llm: LLMConfig | None = Field(default=None, description="LLM configuration for codetour worker")
    qdrant: QdrantConfig = Field(
        default_factory=QdrantConfig,
        description="Qdrant configuration for codetour worker",
    )
    bundler: BundlerConfig = Field(
        default_factory=BundlerConfig,
        description="Bundler worker configuration (Table of Contents, etc.)",
    )
    encryption_key: str = Field(..., description="Encryption key for user configs")
    logfire: LogfireConfig = Field(
        default_factory=LogfireConfig,
        description="Logfire instrumentation for Pydantic-AI agents",
    )
    prompts_dir: Path = Field(
        default=Path("configs/agents"),
        description="Directory with agent prompts",
    )
    health_host: str = Field(
        default="0.0.0.0",
        description="Bind host for the in-worker liveness HTTP server.",
    )
    health_port: int | None = Field(
        default=None,
        description=(
            "Port for the in-worker /health HTTP server. Leave null to fall "
            "back to $HEALTH_PORT or the per-mode default (docgen=8100, "
            "repos=8101, bundler=8102, codetour=8103)."
        ),
    )
    pricing: dict[str, ModelPricing] = Field(
        default_factory=lambda: dict(DEFAULT_MODEL_PRICING),
        description=(
            "Lowercase model name => USD-per-1M-tokens pricing. Used by the "
            "docgen handlers to compute cost_usd alongside token counts. "
            "Missing entries are skipped (cost is recorded as null)."
        ),
    )
    worker_concurrency: int = Field(
        default=12,
        ge=1,
        description=(
            "Max number of concurrent in-flight stream messages per worker process. "
            "Bigger values let multiple per-page handlers (write/diagram/review/etc.) "
            "run truly in parallel; without it the worker awaits each dispatch "
            "serially, throttling throughput to one event at a time. "
            "Embeddings concurrency (`embeddings.concurrency` in the per-task LLM config) "
            "caps parallel embedding requests *within* a single message. "
            "Real per-LLM-call cap is enforced separately by ``LLMConfig.max_sessions`` "
            "(Redis session-lock keyed by sha256(api_key)), so this value can sit "
            "well above the provider's inflight limit without 429-cascading."
        ),
    )

    @field_validator("prompts_dir", mode="before")
    @classmethod
    def resolve_prompts_dir(cls, v: str | Path) -> Path:
        """Resolve prompts_dir to absolute path."""
        path = Path(v)
        if not path.is_absolute():
            project_root = Path(__file__).parent.parent.parent.parent
            mvp_path = (project_root / "core" / "mvp" / path).resolve()
            codetour_path = (project_root / "core" / "codetour" / path).resolve()
            if mvp_path.exists():
                path = mvp_path
            elif codetour_path.exists():
                path = codetour_path
        return path

    @field_validator("pricing", mode="before")
    @classmethod
    def lowercase_pricing_keys(cls, v: object) -> object:
        """Ensure pricing keys are lowercase so lookups don't depend on casing.

        Operators may write `GPT-4o` in YAML; pydantic-AI gives us back
        `gpt-4o` — normalise here so the lookup just works.
        """
        if isinstance(v, dict):
            return {str(k).lower(): val for k, val in v.items()}
        return v


def get_worker_config(config_path: str | Path = "config.yaml") -> GatewayWorkerConfig:
    return load_yaml_config(config_path, GatewayWorkerConfig)


def compute_cost_usd(
    model: str,
    prompt_tokens: int,
    completion_tokens: int,
    pricing: dict[str, ModelPricing],
) -> float | None:
    """Return cost in USD or ``None`` if the model isn't priced.

    Lookups are case-insensitive — pydantic-AI sometimes prefixes provider
    (e.g. ``openai:gpt-4o``); strip it before matching.
    """
    if not model:
        return None
    key = model.lower()
    if ":" in key:
        key = key.split(":", 1)[1]
    rates = pricing.get(key)
    if rates is None:
        return None
    return (
        prompt_tokens * rates.prompt_per_1m / 1_000_000
        + completion_tokens * rates.completion_per_1m / 1_000_000
    )
